# Generated by Django 3.2.4 on 2021-06-10 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votes_to_skipp',
            new_name='votes_to_skip',
        ),
    ]
